modLoader="lowcodefml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="echoes_terrain"
version="1.0"
displayName="Echoes Terrain"
description='''
World generation for the modpack Echoes of the Golden Era.
Fantasy Beta terrain with vanilla underground.
'''
authors="Vkingzz"

[[dependencies.echoes_terrain]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.echoes_terrain]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"